version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ignite_call
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
